version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  api:
    build:
      context: api/.
      dockerfile: Dockerfile
    command: ruby server.rb
    ports:
      - "5678:5678"
    depends_on:
      - db